spring:
  datasource:
    url: jdbc:mysql://${DATABASE_URL}/datshop?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiredAccess: ${JWT_EXPIRED_ACCESS}
  expiredRefresh: ${JWT_EXPIRED_REFRESH}