spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  data:
#    redis:
#      host: localhost
#      port: 6379
#  session:
#    store-type: redis
  main:
    allow-circular-references: true
#  mail:
#    port: 587
#    host: smtp.gmail.com
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
#            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
  profiles:
    active: ${ACTIVE_PROFILE}
  jackson:
    default-property-inclusion: non_null



springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    csrf:
      enabled: true
    path: /swagger-ui.html

ollama:
  embed-model: nomic-embed-text
  chat-model: mistral

server:
  port: 8080
