spring:
  datasource:
    url: jdbc:mysql://localhost:3306/datshop?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: 'Y0doaGJXNW5kWGxsYm5SaGRHUmhkR0YwZEhReU1ESTBMakU9'
  expiredAccess: '1h'
  expiredRefresh: '1d'

vnpay:
  vnp_TmnCode: SKM4V1QG
  vnp_HashSecret: KB00HFAUBXPFJMAWNV8JLFIV8X9B8ZJQ
  vnp_PayUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  vnp_ReturnUrl: http://localhost:8080/api/v1/callback/payment-callback
  vnp_ApiUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction