package com.dat.backend.datshop.chatbot.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

@Service
@RequiredArgsConstructor
public class QdrantService {
    private static final String LEGACY_COLLECTION = "chatbot_rag";

    private final WebClient webClient;
    private final Set<String> initializedCollections = ConcurrentHashMap.newKeySet();

    /**
     * Kept for compatibility with vectors previously generated by nomic-embed-text.
     */
    @Deprecated
    public void upsertVector(String id, double[] vector) throws JsonProcessingException {
        upsertVector(LEGACY_COLLECTION, id, vector);
    }

    public void upsertVector(String collectionName, String id, double[] vector)
            throws JsonProcessingException {
        ensureCollection(collectionName, vector.length);
        List<Double> vectorValues = Arrays.stream(vector).boxed().toList();

        webClient.put()
                .uri("http://localhost:6333/collections/{collectionName}/points?wait=true", collectionName)
                .bodyValue(Map.of(
                        "points", List.of(Map.of(
                                "id", id,
                                "vector", vectorValues
                        ))
                ))
                .retrieve()
                .bodyToMono(Void.class)
                .block();
    }

    /**
     * Kept for compatibility with the original Ollama/Qdrant integration.
     */
    @Deprecated
    public List<Map<String, Object>> searchTopKSimilarProducts(List<Double> vector, int limit)
            throws JsonProcessingException {
        return searchTopKSimilarProducts(LEGACY_COLLECTION, vector, limit);
    }

    @SuppressWarnings("unchecked")
    public List<Map<String, Object>> searchTopKSimilarProducts(
            String collectionName,
            List<Double> vector,
            int limit
    ) throws JsonProcessingException {
        ensureCollection(collectionName, vector.size());
        Object requestBody = Map.of(
                "query", vector,
                "limit", limit,
                "params", Map.of(
                        "hnsw_ef", 128,
                        "exact", false
                )
        );

        // System.out.println(new ObjectMapper().writeValueAsString(requestBody));

        Map<String, Object> response = webClient.post()
                .uri("http://localhost:6333/collections/{collectionName}/points/query", collectionName)
                .bodyValue(requestBody)
                .retrieve()
                .bodyToMono(Map.class)
                .block();

        // System.out.println(new ObjectMapper().writeValueAsString(response));
        if (response == null || response.isEmpty()) {
            return List.of();
        }

        Map<String, Object> result = (Map<String, Object>) response.get("result");
        if (result == null || result.get("points") == null) {
            return List.of();
        }
        return (List<Map<String, Object>>) result.get("points");
    }

    private void ensureCollection(String collectionName, int vectorSize) {
        if (initializedCollections.contains(collectionName)) {
            return;
        }

        synchronized (initializedCollections) {
            if (initializedCollections.contains(collectionName)) {
                return;
            }

            Boolean exists = webClient.get()
                    .uri("http://localhost:6333/collections/{collectionName}", collectionName)
                    .exchangeToMono(response -> response.releaseBody()
                            .thenReturn(response.statusCode().is2xxSuccessful()))
                    .block();

            if (!Boolean.TRUE.equals(exists)) {
                webClient.put()
                        .uri("http://localhost:6333/collections/{collectionName}", collectionName)
                        .bodyValue(Map.of(
                                "vectors", Map.of(
                                        "size", vectorSize,
                                        "distance", "Cosine"
                                )
                        ))
                        .retrieve()
                        .bodyToMono(Void.class)
                        .block();
            }

            initializedCollections.add(collectionName);
        }
    }
}
